version: "3.9"
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: url_short
      MYSQL_USER: USER
      MYSQL_PASSWORD: USER_PASSWORD
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    depends_on:
    - database
    environment:
      JWT_SECRET_KEY: PASSWORD123
      DB_USERNAME: root
      DB_PASSWORD: ROOT_PASSWORD
      DB_HOST: database
      DB_NAME: url_short
      HOST: ":8080"
    ports:
      - "8080:8080"


volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local